kvmd:
    auth:
        enabled: true

    server:
        unix_mode: 0666
        access_log_format: '[%P / %{X-Real-IP}i] ''%r'' => 响应：%s；大小：%b；来源：''%{Referer}i''；用户代理：''%{User-Agent}i'''

    atx:
        type: disabled

    hid:
        type: ch9329
        device: /dev/ttyUSB0

        jiggler:
            active: false
            enabled: true

        mouse_alt:
            device: /dev/kvmd-hid-mouse-alt

    msd:
        #type: otg
        remount_cmd: /bin/true

    ocr:
        langs:
            - eng
            - chi_sim

    streamer:
        resolution:
            default: 1280x720

        forever: true

        desired_fps:
            default: 30
            max: 60

        h264_bitrate:
            default: 2000

        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/video0"
            - "--persistent"
            - "--format=mjpeg"
            - "--encoder=LIBX264-VIDEO"
            - "--resolution={resolution}"
            - "--desired-fps={desired_fps}"
            - "--drop-same-frames=30"
            - "--last-as-blank=0"
            - "--unix={unix}"
            - "--unix-rm"
            - "--unix-mode=0666"
            - "--exit-on-parent-death"
            - "--process-name-prefix={process_name_prefix}"
            - "--notify-parent"
            - "--no-log-colors"
            - "--h264-sink=kvmd::ustreamer::h264"
            - "--h264-sink-mode=0660"
            - "--jpeg-sink=kvmd::ustreamer::jpeg"
            - "--jpeg-sink-mode=0660"
            - "--h264-bitrate={h264_bitrate}"
            - "--h264-gop={h264_gop}"
            - "--slowdown"
    gpio:
        drivers:
            wol_server1:
                type: wol
                mac: 2c:56:dc:db:7c:1e
            short_press:
                type: cmd
                cmd: [/etc/kvmd/atx.sh, short]
            long_press:
                type: cmd
                cmd: [/etc/kvmd/atx.sh, long]
            reset_press:
                type: cmd
                cmd: [/etc/kvmd/atx.sh, reset]
            input1:
                type: cmd
                cmd: [/etc/kvmd/kvm_input.sh, 1]    
            input2:
                type: cmd
                cmd: [/etc/kvmd/kvm_input.sh, 2]
        scheme:
            wol_server1:
                driver: wol_server1
                pin: 0
                mode: output
                switch: false
            short_button:
                driver: short_press
                pin: 0
                mode: output
                switch: false
            long_button:
                driver: long_press
                pin: 0
                mode: output
                switch: false
            reset_button:
                driver: reset_press
                pin: 0
                mode: output
                switch: false
            input1-button:
                driver: input1
                pin: 0
                mode: output
                switch: false
            input2-button:
                driver: input2
                pin: 0
                mode: output
                switch: false
        view:
            header:
                title: 高级功能
            table:
                - ["#电源管理"]
                - ["#短按（开/关机）:", short_button|按下]
                - ["#长按（强制关机）:", long_button|按下]
                - ["#重启:", reset_button|按下]
                - []
                - ["#网络唤醒"]
                - ["#被控机设备", wol_server1|网络唤醒]
                - []
                - ["#KVM 切换"]
                - ["#HDMI 1", input1-button|切换]
                - ["#HDMI 2", input2-button|切换]


vnc:
    keymap: /usr/share/kvmd/keymaps/en-us
    mouse_output: usb

    auth:
        vncauth:
            enabled: true

    memsink:
        jpeg:
            sink: "kvmd::ustreamer::jpeg"
        h264:
            sink: "kvmd::ustreamer::h264"

otgnet:
    commands:
        post_start_cmd:
            - "/bin/true"
        pre_stop_cmd:
            - "/bin/true"

nginx:
    http:
        port: 8080
    https:
        port: 4430


languages:
    console: zh
    web: zh