name: Pico HID CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installing deps ...
        run: sudo apt-get install cmake gcc-arm-none-eabi build-essential

      - name: Running tests ...
        run: make -C hid/pico all
