name: TOX CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building testenv ...
        run: make testenv

      - name: Running tests ...
        run: make tox CMD="tox -c testenv/tox.ini"
